channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.10.4
  - mlflow==1.26.0
  - pip==21.2.4
  - pip:
      - azure-ai-ml==1.2.0
      - azureml-mlflow==1.48.0
      - responsibleai~=0.21.0
      - raiwidgets~=0.21.0